src/Entity/Character.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="characters")
 * @ORM\Entity(repositoryClass="App\Repository\CharacterRepository")
 */
class Character
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=16)
     * @Assert\NotBlank
     * @Assert\Length(
     *     min = 3,
     *     max = 16,
     *)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank
     * @Assert\Length(
     *     min = 3,
     *     max = 16,
     *)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     * @Assert\Length(
     *     min = 3,
     *     max = 16,
     *)
     */
    private $caste;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     * @Assert\Length(
     *     min = 3,
     *     max = 16,
     *)
     */
    private $knowledge;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Range(
     *     min = 0,
     *     max = 250
     * )
     */
    private $intelligence;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Range(
     *     min = 0,
     *     max = 250
     * )
     */
    private $life;

    /**
     * @ORM\Column(type="string", length=128, nullable=true)
     * @Assert\Length(
     *     min = 3,
     *     max = 128,
     *)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=16)
     * @Assert\Length(
     *     min = 3,
     *     max = 16,
     *)
     */
    private $kind;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation;

    /**
     * @ORM\Column(type="string", length=40)
     * @Assert\Length(
     *     min = 40,
     *     max = 40,
     *)
     */
    private $identifier;

    /**
     * @ORM\Column(type="datetime" )
     */
    private $Modification;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Player", inversedBy="characters")
     * @ORM\JoinColumn(nullable=false)
     */
    private $player;
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getCaste(): ?string
    {
        return $this->caste;
    }

    public function setCaste(?string $caste): self
    {
        $this->caste = $caste;

        return $this;
    }

    public function getKnowledge(): ?string
    {
        return $this->knowledge;
    }

    public function setKnowledge(?string $knowledge): self
    {
        $this->knowledge = $knowledge;

        return $this;
    }

    public function getIntelligence(): ?int
    {
        return $this->intelligence;
    }

    public function setIntelligence(?int $intelligence): self
    {
        $this->intelligence = $intelligence;

        return $this;
    }

    public function getLife(): ?int
    {
        return $this->life;
    }

    public function setLife(?int $life): self
    {
        $this->life = $life;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }


    public function getKind(): ?string
    {
        return $this->kind;
    }

    public function setKind(string $kind): self
    {
        $this->kind = $kind;

        return $this;
    }

    public function getCreation(): ?\DateTimeInterface
    {
        return $this->creation;
    }

    public function setCreation(\DateTimeInterface $creation): self
    {
        $this->creation = $creation;

        return $this;
    }

    /**
     * Convert the entity in an array
     * @return array
     */

    public function toArray(bool $expand = true)
    {
        $character =  get_object_vars($this);

        if (null !== $character['creation']) {
            $character['creation'] = $character['creation']->format('Y-m-d H:i:s');
        }

        if (null !== $character['Modification']) {
            $character['Modification'] = $character['Modification']->format('Y-m-d H:i:s');
        }

        if ($expand && null !== $this->getPlayer()) {
            $character['player'] = $this->getPlayer()->toArray(false);
        }
        return $character;
    }

    public function getIdentifier(): ?string
    {
        return $this->identifier;
    }

    public function setIdentifier(string $identifier): self
    {
        $this->identifier = $identifier;

        return $this;
    }

    public function getModification(): ?\DateTimeInterface
    {
        return $this->Modification;
    }

    public function setModification(\DateTimeInterface $Modification): self
    {
        $this->Modification = $Modification;

        return $this;
    }

    public function getPlayer(): ?Player
    {
        return $this->player;
    }

    public function setPlayer(?Player $player): self
    {
        $this->player = $player;

        return $this;
    }
}

src/Form/CharacterType.php
<?php

namespace App\Form;

use App\Entity\Character;
use App\Entity\Player;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class CharacterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('surname', TextType::class)
            ->add('caste', TextType::class)
            ->add('knowledge', TextType::class)
            ->add('intelligence', IntegerType::class)
            ->add('life', IntegerType::class)
            ->add('image', TextType::class)
            ->add('kind', TextType::class)
            ->add('creation', DateTimeType::class)
            ->add('identifier', TextType::class)
            ->add('Modification', DateTimeType::class)
            ->add('player', EntityType::class, [
                // looks for choices from this entity
                'class' => Player::class ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Character::class,
        ]);
    }
}

src/Controller/CharacterController.php
<?php

namespace App\Controller;

use App\Entity\Character;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use App\Service\CharacterServiceInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Nelmio\ApiDocBundle\Annotation\Model;
use Swagger\Annotations as SWG;

class CharacterController extends AbstractController
{
    private $characterService;

    /**
     * CharacterController constructor.
     *
     */
    public function __construct(CharacterServiceInterface $characterService)
    {
        $this->characterService = $characterService;
    }

    /**
     * Redirect to index route
     *
     * @Route("/character",
     *     name="character_redirect_index",
     *     methods={"GET", "HEAD"}
     *     )
     * @SWG\Response(
     *     response=302,
     *     description="Redirect",
     * )
     * @SWG\Tag(name="Character")
     */
    public function redirectIndex()
    {
        return $this->redirectToRoute('character_index');
    }


    /**
     * Displays available Characters
     *
     * @Route("/character/index",
     *     name="character_index",
     *     methods={"GET", "HEAD"}
     *     )
     *
     * @SWG\Response(
     *     response=200,
     *     description="Success",
     *     @SWG\Schema(
     *      type="array",
     *      @SWG\Items(ref=@Model(type=Character::class))
     *      )
     * )
     * @SWG\Response(
     *     response=403,
     *     description="Access denied"
     * )
     * @SWG\Tag(name="Character")
     */
    public function index()
    {
        $this->denyAccessUnlessGranted('characterIndex', null);
        $characters = $this->characterService->getAll();

        return new JsonResponse($characters);
    }

    /**
     * Displays available Characters by intelligence
     *
     * @Route("/character/index/{intelligence}",
     *     name="character_index_intelligence",
     *     methods={"GET", "HEAD"}
     *     )
     *
     * @SWG\Response(
     *     response=200,
     *     description="Success",
     *     @SWG\Schema(
     *      type="array",
     *      @SWG\Items(ref=@Model(type=Character::class))
     *      )
     * )
     * @SWG\Response(
     *     response=403,
     *     description="Access denied"
     * )
     * @SWG\Tag(name="Character")
     */
    public function indexIntelligence($intelligence)
    {
        $this->denyAccessUnlessGranted('characterIndexIntelligence', null);
        $characters = $this->characterService->getAllByIntelligence($intelligence);

        return new JsonResponse($characters);
    }

    /**
     * Display character
     *
     * @Route("/character/display/{identifier}",
     *     name="character_display",
     *     requirements={"identifier": "^([a-z0-9]{40})$"},
     *     methods={"GET", "HEAD"})
     * @Entity("character", expr="repository.findOneByIdentifier(identifier)")
     *
     * @SWG\Response(
     *     response=200,
     *     description="Success",
     * @Model(type=Character::class)
     * )
     * @SWG\Response(
     *     response=403,
     *     description="Access denied"
     * )
     * @SWG\Response(
     *     response=404,
     *     description="Not found"
     * )
     * @SWG\Tag(name="Character")
     */

    public function display(Character $character)
    {
        $this->denyAccessUnlessGranted('characterDisplay', $character);

        return new JsonResponse($character->toArray());
    }

    //CREATE
    /**
     * Create character
     *
     * @Route("/character/create",
     *     name="character_create",
     *     methods={"POST","HEAD"}
     *     )
     * @SWG\Response(
     *     response=200,
     *     description="Success",
     * @Model(type=Character::class)
     * )
     * @SWG\Response(
     *     response=403,
     *     description="Access denied"
     * )
     * @SWG\Parameter(
     *     name="request",
     *     in="body",
     *     description="Data for the Character",
     *     required=true,
     *     @Model(type=App\Form\CharacterType::class)
     * )
     * @SWG\Tag(name="Character")
     */

    public function create(Request $request)
    {
        $this->denyAccessUnlessGranted('characterCreate', null);

        $character = $this->characterService->create($request->getContent());

        return new JsonResponse($character->toArray());
    }

    /**
     * Modify character
     *
     * @Route("/character/modify/{identifier}",
     *    name="character_modify",
     *    requirements={"identifier": "^([a-z0-9]{40}$)"},
     *    methods={"PUT", "HEAD"})
     *
     *
     * @SWG\Response(
     *     response=200,
     *     description="Success",
     * @Model(type=Character::class)
     * )
     * @SWG\Response(
     *     response=403,
     *     description="Access denied"
     * )
     * @SWG\Parameter(
     *     name="request",
     *     in="path",
     *     description="Data for the Character",
     *     required=true,
     *    type="string"
     * )
     *      * @SWG\Parameter(
     *     name="request",
     *     in="body",
     *     description="Data for the Character",
     *     required=true,
     *     @Model(type=App\Form\CharacterType::class)
     * )
     * @SWG\Tag(name="Character")
     */
    public function modify(Character $character, Request $request)
    {
        $this->denyAccessUnlessGranted('characterModify', $character);
        $character = $this->characterService->modify($character, $request->getContent());
        return new JsonResponse($character->toArray());
    }

    /**
     * Delete character
     *
     * @Route("/character/delete/{identifier}",
     *    name="character_delete",
     *    requirements={"identifier": "^([a-z0-9]{40}$)"},
     *    methods={"DELETE", "HEAD"})
     *
     * @SWG\Response(
     *     response=200,
     *     description="Success",
     *     @SWG\Schema(
     *      @SWG\Property(property="delete", type="boolean")
     *  )
     * )
     * @SWG\Response(
     *     response=403,
     *     description="Access denied"
     * )
     * @SWG\Parameter(
     *     name="request",
     *     in="path",
     *     description="Data for the Character",
     *     required=true,
     *    type="string"
     * )
     * @SWG\Tag(name="Character")
     */
    public function delete(Character $character)
    {
        $this->denyAccessUnlessGranted('characterDelete', $character);
        $character = $this->characterService->delete($character);
        return new JsonResponse($character->toArray());
    }
}

templates/character/_delete_form.html.twig
<form method="post" action="{{ path('character_delete_html', {'identifier': character.identifier}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ character.identifier) }}">
    <button class="btn">Delete</button>
</form>

templates/character/_form.html.twig
{{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/character/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un nouveau personnage{% endblock %}

{% block body %}
<div class="d-flex p-5 flex-column align-items-center justify-content-center">
    <div class="w-50">
        <h1>Créer un nouveau personnage</h1>

        {{ include('character/_form.html.twig') }}

        <a href="{{ path('character_index_html') }}">Retour à la liste</a>
    </div>
</div>
{% endblock %}

templates/character/display.html.twig
{% extends 'base.html.twig' %}

{% block title %}Character{% endblock %}

{% block body %}
    <h1>Character</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ character.id }}</td>
            </tr>
            <tr>
                <th>Kind</th>
                <td>{{ character.kind }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ character.name }}</td>
            </tr>
            <tr>
                <th>Surname</th>
                <td>{{ character.surname }}</td>
            </tr>
            <tr>
                <th>Caste</th>
                <td>{{ character.caste }}</td>
            </tr>
            <tr>
                <th>Knowledge</th>
                <td>{{ character.knowledge }}</td>
            </tr>
            <tr>
                <th>Intelligence</th>
                <td>{{ character.intelligence }}</td>
            </tr>
            <tr>
                <th>Life</th>
                <td>{{ character.life }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ character.image }}</td>
            </tr>
            <tr>
                <th>Identifier</th>
                <td>{{ character.identifier }}</td>
            </tr>
            <tr>
                <th>Creation</th>
                <td>{{ character.creation ? character.creation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Modification</th>
                <td>{{ character.modification ? character.modification|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('character_index_html') }}">back to list</a>

    <a href="{{ path('character_modify_html', {'identifier': character.identifier}) }}">edit</a>

    {{ include('character/_delete_form.html.twig') }}
{% endblock %}

templates/character/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Listes des personnages{% endblock %}

{% block body %}
    <h1>Listes des personnages</h1>


{# Entête du tableau #}
    <table class="table text-center table-hover">
        <thead>
            <tr>
                <th>Kind</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Caste</th>
                <th>Knowledge</th>
                <th>Intelligence</th>
                <th>Life</th>
                <th>Creation</th>
                <th>Modification</th>
                <th>actions</th>
            </tr>
        </thead>

        <tbody>
        {% for character in characters %}
{# Valuers d'un personnage #}
            <tr>
                {% if character.kind == "Dame" %}
                        <td><strong>{{ character.kind }}</strong></td>
                {% else %}
                    <td>{{ character.kind }}</td>
                {% endif %}
                <td><a href="{{ path('character_display_html', {'identifier': character.identifier}) }}"> {{ character.name }}</a></td>
                <td>{{ character.surname }}</td>
                <td>{{ character.caste }}</td>
                <td>{{ character.knowledge }}</td>
                <td>{{ character.intelligence }}</td>
                <td>{{ character.life }}</td>
                <td>{{ character.creation ? character.creation|date('d-m-Y') : '' }}</td>
                <td>{{ character.Modification ? character.Modification|date('d-m-Y') : '' }}</td>
                <td>
                    <a href="{{ path('character_modify_html', {'identifier': character.identifier}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="d-flex w-20 justify-content-center" href="{{ path('character_create_html') }}">Nouveau Personnage</a>
{% endblock %}

templates/character/modify.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Character{% endblock %}

{% block body %}
    <h1>Edit Character</h1>

    {{ include('character/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('character_index_html') }}">back to list</a>

    {{ include('character/_delete_form.html.twig') }}
{% endblock %}